---
- hosts: all
  connection: local
  tasks:
  # - debug:
  #     var: ansible_facts

  - name: Do the thingy.
    when: "ansible_facts['processor_cores'] != 2"
    shell:
      cmd: "echo 'woot!'"

  - name: Do the other thingy.
    when: ansible_facts['processor_cores'] == 2
    shell:
      cmd: "echo 'kowabunga it is!'"
