---
 - hosts: localhost
   tasks:
   - name: Ensure docker group is present.
     group: name=docker state=present

   - name: Setup Adobe yum repo.
     shell: '/usr/bin/rpm -ivh http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm ||:'

   - name: Capture Fedora release number.
     shell: '/bin/rpm -E %fedora'
     register: rpm_release

   # I've seen the non-free rpmfusion rpm not get installed. Would love to know why.
   - name: Enable RPMFusion
     dnf: name=https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ rpm_release.stdout }}.noarch.rpm       state=latest
     dnf: name=https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ rpm_release.stdout }}.noarch.rpm state=latest

   - name: Install libselinux.
     dnf: name={{ item }} state=latest
     with_items:
       - libselinux-python
       - libselinux-python3

   - name: Setup Google Chrome repo file.
     copy: src=~/git/main-engineering/google-chrome.repo dest=/etc/yum.repos.d/google-chrome.repo owner=root group=root mode=0644

   - name: Setup VirtualBox Repo.
     copy: src=~/git/main-engineering/VirtualBox.repo dest=/etc/yum.repos.d/VirtualBox.repo owner=root group=root mode=0644

   - name: Import Google Chrome public key.
     shell: '/bin/rpm --import https://dl-ssl.google.com/linux/linux_signing_key.pub'

   - name: Create a plasma configuration directory.
     become: true
     become_user: merlin
     shell: '/bin/mkdir -p /home/merlin/.config/plasma-workspace/env'

   - name: Create a file to set KDEs default window manager to xmonad.
     copy: src=~/git/main-engineering/set_window_manager.sh dest=/home/merlin/.config/plasma-workspace/env

   - name: Enable the Haskell Stack COPR repo.
     shell: 'dnf copr enable petersen/stack -y'

   - name: Install packaged development tools.
     dnf: name={{ item }} state=present
     with_items:
       - ack
       - asciidoc
       - boost-static
       - colordiff
       - colorgcc
       - cabal-rpm
       - cargo
       - clang
       - cmake
       - clojure
       - cowsay
       - cppcheck
       - emacs
       - dash
       - fish
       - haskell-platform
       - hlint
       - gcc-c++
       - gem
       - git
       - git-extras
       - git-svn
       - golang
       - htop
       - hub
       - levien-inconsolata-fonts
       - iftop
       - iotop
       - irssi
       - lynx
       - mercurial
       - mc
       - most
       - npm
       - ntop
       - perl-core
       - perl-criticism
       - perltidy
       - php-pear
       - pv
       - python
       - PyYAML
       - rpmlint
       - rust
       - rust-doc
       - rust-lldb
       - rust-src
       - rust-std-static
       - screen
       - stack
       - strace
       - subversion
       - the_silver_searcher
       - tmux
       - vim-enhanced
       - vim-X11
       - zsh

   # Doing this the caveman way because the npm ansible module doesn't react
   # well with the with_items: construct.
   - name: Install npm packages.
     shell: 'npm install --global\
     acorn\
     eslint\
     eslint-config-standard\
     eslint-plugin-react\
     js-beautify\
     jshint\
     standard\
     tern'

   - name: Install Gem package ().
     gem:
       name: sqlint
       state: latest

   - name: Install Pear packages (phpcs).
     pear:
       name: PHP_CodeSniffer
       state: latest

   - name: Install pip packages (powerline).
     pip:
       name: powerline-status
       state: latest

   - name: Install -devel packages for threadscope.
     dnf: name={{ item }}
     state: present
     with_items:
       - cairo-devel
       - glib2-devel
       - gtk2-devel
       - pango-devel

   - name: Install packaged desktop tools.
     dnf: name={{ item }}
     state: present
     with_items:
       - GraphicsMagick
       - ImageMagick
       - NetworkManager-tui
       - VirtualBox-5.1 # Needs the virtualbox repo.
       - amarok-utils
       - darktable
       - digikam
       - dkms
       - dmenu
       - docker-io
       - dzen2
       - exfat-utils
       - firefox
       - flash-plugin
       - fortune-mod
       - free42
       - fuse-exfat
       - gimp
       - google-chrome-stable # Needs the google chrome repo.
       - gparted
       - gpodder
       - imlib2
       - imlib2-devel
       - kdenlive
       - kernel-devel
       - kernel-headers
       - libXpm-devel
       - libxml2-static
       - libxml++-devel
       - libxml++30-devel
       - libxml-devel
       - obs-studio
       - paman
       - paprefs
       - pavucontrol
       - pavumeter
       - pidgin
       - pidgin-otr
       - plasma-applet-redshift-control
       - purple-plugin-pack
       - redshift
       - seamonkey
       - sl
       - sysstat
       - tigervnc
       - ufraw
       - unetbootin
       - vnstat
       - wireless-tools-devel
       - xcompmgr
       - Xdialog
       - xmonad
       - xsel
       - yakuake

   - name: Checkout Dotfiles repo.
     become: true
     become_user: merlin
     git: repo=https://github.com/TheWizardTower/abrazo.git
          dest=/home/merlin/abrazo
          accept_hostkey=yes
          update=no

   - name: Checkout a copy of Spacemacs.
     become: true
     become_user: merlin
     git: repo=https://github.com/syl20bnr/spacemacs.git
          dest=/home/merlin/spacemacs/.emacs.d
          accept_hostkey=true
          update=yes

   - name: Checkout a copy of Tmux Plugin Manager
     become: true
     become_user: merlin
     git:
       repo: https://github.com/tmux-plugins/tpm
       dest: /home/merlin/.tmux/plugins/tpm
       accept_hostkey: true
       update: yes

   - name: Create ~/git
     become: true
     become_user: merlin
     file: path=/home/merlin/git state=directory

   # Need to make the ~/git dir
   - name: Checkout useful git repos.
     become: true
     become_user: merlin
     git: repo={{ item.src }}
          accept_hostkey=true
          dest=/home/merlin/git/{{ item.dest }}
          update=yes 
     with_items:
       - { src: 'https://github.com/Airblader/xcb-util-xrm.git', dest: 'xcb-util-xrm' }
       - { src: 'https://github.com/DanielG/cabal-helper.git', dest: 'cabal-helper' }
       - { src: 'https://github.com/DanielG/ghc-mod.git', dest: 'ghc-mod' }
       - { src: 'https://github.com/LuRsT/hr.git', dest: 'hr' }
       - { src: 'https://github.com/agda/agda.git', dest: 'agda' }
       - { src: 'https://github.com/alanz/HaRe.git', dest: 'HaRe' }
       - { src: 'https://github.com/carlohamalainen/ghc-imported-from', dest: 'ghc-imported-from' }
       - { src: 'https://github.com/creichert/stack-tag.git', dest: 'stack-tag' }
       - { src: 'https://github.com/edc/bass.git', dest: 'bass' }
       - { src: 'https://github.com/favadi/flycheck-gometalinter.git', dest: 'flycheck-gometalinter' }
       - { src: 'https://github.com/garabik/grc.git', dest: 'grc' }
       - { src: 'https://github.com/github/hub.git', dest: 'hub' }
       - { src: 'https://github.com/jonas/tig.git', dest: 'tig' }
       - { src: 'https://github.com/joshuaclayton/unused.git', dest: 'unused' }
       - { src: 'https://github.com/junegunn/fzf.git', dest: 'fzf' }
       - { src: 'https://github.com/kanaka/mal.git', dest: 'mal' }
       - { src: 'https://github.com/kanaka/mal.workshop.git', dest: 'mal.workshop' }
       - { src: 'https://github.com/ndmitchell/ghcid.git', dest: 'ghcid' }
       - { src: 'https://github.com/powerline/fonts.git', dest: 'fonts' }
       - { src: 'https://github.com/replicatedhq/dockerfilelint.git', dest: 'dockerfilelint' }
       - { src: 'https://github.com/sboli/twmn.git', dest: 'twmn' }
       - { src: 'https://github.com/thestinger/termite.git', dest: 'termite' }
       - { src: 'https://github.com/thestinger/vte-ng.git', dest: 'vte-ng' }
       - { src: 'https://github.com/tj/git-extras.git', dest: 'git-extras' }
       - { src: 'https://github.com/unixorn/git-extra-commands.git', dest: 'git-extra-commands' }
       - { src: 'https://gitlab.com/o9000/tint2.git', dest: 'tint2' }

   - name: Setup fonts.
     become: true
     become_user: merlin
     shell: "/home/merlin/git/fonts/install.sh"

   - name: Setup bass.
     become: true
     become_user: merlin
     shell: "make install"
     args:
       chdir: /home/merlin/git/bass

   - name: Setup GRC.
     shell: "/home/merlin/git/grc/install.sh"
     args:
       chdir: /home/merlin/git/grc

   - name: Install hr.
     shell: "make install"
     args:
       chdir: /home/merlin/git/hr

   - name: Build tig.
     become: true
     become_user: merlin
     shell: "make; make install; make install-doc; make install-release-doc"
     args:
       chdir: /home/merlin/git/tig

   - name: Setup abrazo dotfiles repo.
     become: true
     become_user: merlin
     shell: "/home/merlin/dotfiles/install"
     args:
       chdir: /home/merlin/dotfiles
  
   - name: Update packages.
     dnf: name=* state=latest
  
