---
 - hosts: all
   tasks:
   - name: Ensure docker group is present.
     group: name=docker state=present

   - name: Setup Adobe yum repo.
     shell: '/usr/bin/rpm -ivh http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm ||:'

   - name: Setup Google Chrome repo file.
     copy: src=/home/amccullough/git/ansible/google-chrome.repo dest=/etc/yum.repos.d/google-chrome.repo owner=root group=root mode=0644

   - name: Import Google Chrome public key.
     shell: '/bin/rpm --import https://dl-ssl.google.com/linux/linux_signing_key.pub'

   - name: Create a plasma configuration directory.
     become: true
     become_user: amccullough
     shell: '/bin/mkdir -p /home/amccullough/.config/plasma-workspace/env status=directory'

   - name: Create a file to set KDEs default window manager to xmonad.
     copy: src=/home/amccullough/git/ansible/set_window_manager.sh dest=/home/amccullough/.config/plasma-workspace/env

   - name: Install packaged development tools.
     dnf: name={{ item }} state=present
     with_items:
       - ack
       - colordiff
       - cabal-rpm
       - clojure
       - emacs
       - dash
       - fish
       - haskell-platform
       - hlint
       - git
       - git-svn
       - golang
       - htop
       - levien-inconsolata-fonts
       - iftop
       - iotop
       - irssi
       - lynx
       - mercurial
       - mc
       - ncurses-compat-libs-6.0-5.20160116.fc24.x86_64
       - ntop
       - perl-core
       - perl-criticism
       - perltidy
       - python
       - PyYAML
       - rpmlint
       - screen
       - stack
       - strace
       - subversion
       - the_silver_searcher
       - tmux
       - vim-enhanced
       - vim-X11
       - zsh

   - name: Install packaged desktop tools.
     dnf: name={{ item }}
          state=present
     with_items:
       - amarok-utils
       - cairo-dock
       - cowsay
       - dmenu
       - darktable
       - digikam
       - dkms
       - docker-io
       - dzen2
       - fedup
       - firefox
       - flash-plugin
       - free42
       - fortune-mod
       - GraphicsMagick
       - gimp
       - google-chrome-stable # Needs the google chrome repo.
       - gparted
       - gpodder
       - ImageMagick
       - imlib2
       - imlib2-devel
       - kernel-devel
       - kernel-headers
       - libsrvg
       - libsrvg-devel
       - NetworkManager-tui
       - paman
       - paprefs
       - pavucontrol
       - pavumeter
       - pidgin
       - pidgin-otr
       - purple-plugin-pack
       - pv
       - redshift
       - seamonkey
       - sl
       - skype
       - steam
       - sysstat
       - tigervnc
       - ufraw
       - unetbootin
       - VirtualBox-5.0 # Needs the virtualbox repo.
       - vlc
       - vnstat
       - xcompmgr
       - xmonad
       - xulrunner
       - yakuake
  
   - name: Checkout utility repos.
     become: true
     become_user: amccullough
     git: repo={{ item }}
          dest=/home/amccullough/{{ item }}
          accept_hostkey=true
          update=yes
     with_items:
       - https://github.com/powerline/fonts.git
       - https://github.com/junegunn/fzf.git


   - name: Checkout Dotfiles repo.
     become: true
     become_user: amccullough
     git: repo=https://github.com/TheWizardTower/dotfiles.git
          dest=/home/amccullough/dotfiles
          accept_hostkey=yes
          update=no

   - name: Checkout a copy of Spacemacs.
     become: true
     become_user: amccullough
     git: repo=https://github.com/syl20bnr/spacemacs.git
          dest=/home/amccullough/spacemacs/.emacs.d
          accept_hostkey=true
          update=yes

   - name: Create ~/git
     become: true
     become_user: amccullough
     file: path=/home/amccullough/git state=directory

   # Need to make the ~/git dir
   - name: Checkout useful git repos.
     become: true
     become_user: amccullough
     git: repo={{ item.src }}
          accept_hostkey=true
          dest=/home/amccullough/git/{{ item.dest }}
          update=yes 
     with_items:
       - { src: 'https://github.com/agda/agda.git', dest: 'agda' }
       - { src: 'https://github.com/edc/bass.git', dest: 'bass' }
       - { src: 'https://github.com/DanielG/cabal-helper.git', dest: 'cabal-helper' }
       - { src: 'https://github.com/replicatedhq/dockerfilelint.git', dest: 'dockerfilelint' }
       - { src: 'https://github.com/favadi/flycheck-gometalinter.git', dest: 'flycheck-gometalinter' }
       - { src: 'https://github.com/junegunn/fzf.git', dest: 'fzf' }
       - { src: 'https://github.com/carlohamalainen/ghc-imported-from', dest: 'ghc-imported-from' }
       - { src: 'https://github.com/DanielG/ghc-mod.git', dest: 'ghc-mod' }
       - { src: 'https://github.com/unixorn/git-extra-commands.git', dest: 'git-extra-commands' }
       - { src: 'https://github.com/tj/git-extras.git', dest: 'git-extras' }
       - { src: 'https://github.com/garabik/grc.git', dest: 'grc' }
       - { src: 'https://github.com/alanz/HaRe.git', dest: 'HaRe' }
       - { src: 'https://github.com/LuRsT/hr.git', dest: 'hr' }
       - { src: 'https://github.com/kanaka/mal.git', dest: 'mal' }
       - { src: 'https://github.com/kanaka/mal.workshop.git', dest: 'mal.workshop' }
       - { src: 'https://github.com/creichert/stack-tag.git', dest: 'stack-tag' }
       - { src: 'https://github.com/thestinger/termite.git', dest: 'termite' }
       - { src: 'https://gitlab.com/o9000/tint2.git', dest: 'tint2' }
       - { src: 'https://github.com/sboli/twmn.git', dest: 'twmn' }
       - { src: 'https://github.com/thestinger/vte-ng.git', dest: 'vte-ng' }
       - { src: 'https://github.com/Airblader/xcb-util-xrm.git', dest: 'xcb-util-xrm' }

   - name: Setup dotfiles repo.
     become: true
     become_user: amccullough
     shell: "/home/amccullough/dotfiles/install.sh"
     args:
       chdir: /home/amccullough/dotfiles
  
   - name: Update packages.
     dnf: name=* state=latest
  
